### ISSUE TITLE
feature: "Toggle Auto Refresh" status should be reflected visually

### ISSUE THREAD

**Issue by lukastribus** [netfishers-onl/BLT#5]
The icon "Toogle Auto Refresh" should visually reflect whether its enabled or disabled. Otherwise, the user has to guess if its enabled or disabled currently.

**Comment by AlainMoretti** [comment]
Yes makes sense. 
I will fix this.

**Comment by AlainMoretti** [comment]
This issue is fixed in [that commit](https://github.com/netfishers-onl/BLT/commit/5654a353cda1ecc7c144db55bde8d5727ff1d876)
Will be integrated in a next to come maintenance release.

**Comment by lukastribus** [comment]
Thanks!
