### ISSUE TITLE
Dijkstra shortest path message should be in foreground

### ISSUE THREAD

**Issue by lukastribus** [netfishers-onl/BLT#7]
The Dijkstra shortest path message should be in the foreground, otherwise it may not be readable:

http://www.bilder-upload.eu/show.php?file=771430-1463152220.png

Also, similar to the other issue, it may be a good idea to show this message near the destination node, instead of a static location.

**Comment by AlainMoretti** [comment]
OK I have to evaluate several options to do this.

**Comment by AlainMoretti** [comment]
Since [last commit](https://github.com/netfishers-onl/BLT/commit/9cdc77e062e17c027dce61cfdfe9139fcd455a59) the legend box is now in foreground. 
For the same reason that issue #6 I couldn't relocate legendbox without some regression for users that expect it at the bottom left of the main window.
